### PR TITLE
#166265835 Set up prettier, using lint-staged config.

### PR DESCRIPTION
**Pull request by encodedBicoding**
### What does this PR do?
Set up Prettier code format-er, and uses lint-staged configuration.
What this actually does is checks for the files on the staging area done by `git add` and fixes any format errors in the file.
#### Description of Task to be completed?
1. Install prettier npm package, along with eslint-config-prettier in dev dependency.
2. run `npx mrm lint-staged` this will install and configure the `husky` package and also configure `lint-staged` object in `package.json`
#### How should this be manually tested?
N/A
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166265835](https://www.pivotaltracker.com/story/show/166265835)

#### Screenshots (if appropriate)
Screenshot (51)

#### Questions:
N/A

### CODE REVIEW

**Review by Hadeneekeh — DISMISSED** [review]

**Review by cvjude — DISMISSED** [review]

**Comment by cvjude** [comment]
Dominic Do a rebase on this branch

**Review by emp-daisy — CHANGES_REQUESTED** [review]
Remove all the `.idea/` files in your commit

**Review by encodedBicoding — COMMENTED** [review]
I have done all the requested changes

**Review by chuxmykel — DISMISSED** [review]
Great job with the setup Dominic. Although the `.idea` files were added to the `.gitignore` file, it still doesn't look like they've been deleted. I think you should delete them explicitly.

**Review by OvieMudi — CHANGES_REQUESTED** [review]
The `.idea` files are still showing up because it is being tracked by your local repo.
You have to either delete them explicitly as Chuks said, or you manually remove them from your tracked files.
Then you can commit the changes.

**Review by encodedBicoding — COMMENTED** [review]
I have done all those. Still don't know why. I guess i will just change my IDE. Which i honestly do not want to, but it seems i have no choice here.

**Review by Hadeneekeh — APPROVED** [review]
Well done @encodedBicoding!!!

**Review by OvieMudi — APPROVED** [review]

**Review by emp-daisy — APPROVED** [review]

**Pull request merged**
